[package]
name = "weather_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
weather_lib = { path = "../weather_lib" }
clap = { version = "4.5.41", features = ["derive"] }
dotenv = "0.15"
tokio = { version = "1.46.1", features = ["full"] }