[package]
name = "weather_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
openweathermap_lib = { version = "0.1.0-pre.2" }
clap = { version = "4.5.41", features = ["derive"] }
dotenv = "0.15"
tokio = { version = "1.46.1", features = ["full"] }